### ISSUE TITLE
Graph layout

### ISSUE THREAD

**Issue by shayo** [open-ephys/GUI#111]
Hi,

I want to bring up for discussion again the issue of displaying the processing graph. Right now, the current approach is OKish for a small graph, but when the number of nodes gets large (specially with multiple split/merge) it becomes very cumbersome to search for a specific processor with the current UI.

Graph layout is a difficult problem. There are some open libraries that can solve the problem, but they are quite big and not very intuitive to use for our needs (e.g., http://igraph.sourceforge.net/index.html, http://www.ogdf.net/)

Ideally, it would be great if you could pass to one of these libraries the graph structure and it could return to you the position, width and height of each node that needs to be drawn. This would make things very easy to integrate. However, most libraries don't supply this, and do most of the drawing themselves, which makes interfacing with them hard.

The closest thing I found that can do this is GraphViz. However, GraphViz is setup as a set of executables. One of the executable is called "dot", which takes as input a simple graph structure, and can output a simple text describing exactly where each node needs to be drawn. (see http://www.graphviz.org/pdf/dotguide.pdf, see -Tplain option). It works very well, and parsing the output is a breeze.

So, this might be an easy hack. Every time the graph changes, we can generate a temporary text input file, run dot on it, parse the text output, and update internally the position of nodes. The disadvantage is that this is a somewhat large package (at least, the windows folder is ~30MB, and the dot.exe depends on many dll files).
One plus is that GraphViz executables are available for linux and mac, so this solution could run on all platforms.

Does someone has a better idea?

-- Shay

**Comment by jsiegle** [comment]
The graph display has been completely overhauled in the latest version of the GUI. These issues should be fixed.
