### ISSUE TITLE
Splitting PSTH module into a processor & visualizer sink

### ISSUE THREAD

**Issue by shayo** [open-ephys/GUI#115]
I'm not planning to do this in the near future, but I was thinking that it would probably be better to split the existing PSTH module into a processor and a sink. This might be useful if other modules would want to gain easy access to firing rates and trial information. IT would be easier to create sinks that do various visualization that needs trial-aligned data (say, spectograms / neurometric curves / ...).

**Comment by jsiegle** [comment]
The PSTH plugin has been substantially refactored and now lives here: https://github.com/open-ephys-plugins/online-psth

If you need this feature for your experiments, please open a new issue in that repository.
