### ISSUE TITLE
FPGA doesn't always find amplifier chips

### ISSUE THREAD

**Issue by jsiegle** [open-ephys/GUI#117]
Occasionally, the GUI pauses while the Rhythm FPGA is "Checking for connected amplifier chips..." After a few seconds, it spits out "error submitting URB: Cannot allocate memory" a bunch of times, then continues on as though no headstages were connected.

If I delete the processor and reload, everything works fine.

Also, this never happened before, so I'm wondering if it's due to some recent changes in the RHD2000Thread. It's occurred with multiple acquisition boards, so I don't think it's a fluke.

**Comment by cxrodgers** [comment]
I also have this problem intermittently. Here is the output:

``
Initializing acquisition board.
Sample rate set to 30000
Error reaping URB: Interrupted system callSample rate set to 30000
Number of enabled data streams: 8
Checking for connected amplifier chips...
Error reaping URB: Interrupted system call
error submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryNumber of enabled data streams: 0
Sample rate set to 30000
  Adding node to graph with ID number 100
``

Sometimes there can be many more messages. At this point I usually kill the open-ephys process, and then there are more of the same error:

Rhythm FPGA updating settings.
Rhythm FPGA setting num outputs to 0
Setting buffer address to 0x2e467f0
Input buffer address is 0x2e467f0
Disabling processors...
Disabling Record Node
Disabling Audio Node
Disabling Message Center
Disabling Rhythm FPGA
Source node received disable signal
RHD2000 data thread stopping acquisition.
Thread exited.
Flushing FIFO.
error submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror submitting URB: Cannot allocate memoryerror usb control message: Cannot allocate memoryerror usb control message: Cannot allocate memoryNumber of 16-bit words in FIFO: 0
error usb control message: Cannot allocate memorySourceNode returning true.
Filter Viewport enabled.

Saving window bounds.

DISABLING DATAVIEWPORT CONNECTION
Sources/Rhythm FPGA
Create subnodes with parameters
  Moving forward along signal chain.
  No processor found.
  End of chain.
RHD2000 interface destroyed.
error usb control message: Cannot allocate memoryerror usb control message: Cannot allocate memory

**Comment by cxrodgers** [comment]
I'm pretty sure the problem occurs between the two consecutive "Sample rate set to 30000" lines. If the GUI hangs at this point, then the problem always occurs; if the GUI proceeds smoothly through this point, then the problem does not occur.

For me, it happens exactly every other time that I start the GUI.

**Comment by aacuevas** [comment]
URB errors are caused by libusb when there is bad communication with the Opal Kelly Front Panel library. This often happens when said lib cannot handle the data transfer in a timely manner (the lib version we're using has poor performance on linux. We're looking into that) or when some error puts it on an undefined state. In any case, once you get this error, you need to completely unplug the FPGA for the library to reset itself.

This doesn't seem to be a bandwidth-related error, though. I'll look for any possible race conditions that might be causing this.

**Comment by jsiegle** [comment]
This has now been fixed.
