### ISSUE TITLE
Feature request: notch filter

### ISSUE THREAD

**Issue by shayo** [open-ephys/GUI#126]
I realized today no one has implemented a notch filter yet... I'm going to work on it tomorrow.

**Comment by nmhettema** [comment]
Where can I find this in the software? The current version only seems to have a bandpass filter.

**Comment by jsiegle** [comment]
The GUI development now takes place in the [plugin-GUI](https://github.com/open-ephys/plugin-GUI) repository. It looks like this change was never merged into the main code base, so there's no notch filter module available in the latest version. If you open an issue in the other repo, we can add this feature to our to-do list.

**Comment by Phosphoenix** [comment]
For people looking for the issue in the plugin repo:
February 2023: https://github.com/open-ephys/plugin-GUI/issues/555
March 2021: https://github.com/open-ephys/plugin-GUI/issues/421

Conclusion, not implemented yet but 'if you are trying to remove noise from a narrow frequency band (eg 60Hz interference) we recommend using the [Common Average Reference ](https://open-ephys.github.io/gui-docs/User-Manual/Plugins/Common-Average-Reference.html) plugin for this instead'.
