### ISSUE TITLE
crashes while setting TTL Out High

### ISSUE THREAD

**Issue by ankit--sethi** [open-ephys/GUI#133]
I'm trying to set the TTL Out pins on the acquisition box to high when a ripple is detected but the program is crashing when run over multiple ripple detections. The program manages to exit fine if it stops after one detection though.

Here're the changes I made:
1) I exposed the Rhd2000EvalBoard::setTtlOut( ) method by adding the following function to RHD2000Thread.cpp/.h
void RHD2000Thread::setTTLPins(int ttlOutArray[ ])
{
    evalBoard->setTtlOut(ttlOutArray);
}

2) Exactly like in FPGAOutput::updateSettings( ), I go up the signal chain and get a pointer (RHD2000Thread\* dataThread) that points to the the rhythm board.

dataThread = (RHD2000Thread*) s->getThread();

3) In my process( ) method for ripple detection, when a ripple gets detected, I'm setting the pins high thus:
dataThread->setTTLPins(ttlOutArray);

The code works fine for the first ripple detection, but after a few more events, I eventually start getting "error reaping URB" messages on the terminal and the whole thing freezes up.

Any ideas as to what this could be? Also, is this the best way to be doing this? I've noticed that FPGAOutput.cpp seems to be using ActionListeners, although it isn't clear to me where the actions attached to "HI" and "LO" (the ActionMessages) are being defined. I assume they call the FPGAThread::setOutputHigh( ) method somehow?

**Comment by jsiegle** [comment]
Setting the TTL output state is now done using the **Acq. Board Output** plugin, and seems to be stable so far.
