### ISSUE TITLE
PSTH sink is slow

### ISSUE THREAD

**Issue by shayo** [open-ephys/GUI#139]
Seems like PSTH processor is pretty slow. I get on average (for a modest 6 conditions)
0.3 ms cost per LFP channel and 0.8 ms per isolated unit. This time is spent to do averaging & interpolation of the actual data points.

Doing the math: 64 channels with an average of 2 units on each comes up to be > 100 ms. 

Solution? Creating a Threadpool that will handle the averaging.
8 cores might reduce this to about 20 ms.

Other options would be to significantly optimize the critical functions, but they are already pretty minimal.

**Comment by jsiegle** [comment]
The PSTH plugin has been substantially refactored and now lives here: https://github.com/open-ephys-plugins/online-psth

Please document any performance issues in that repository.
