### ISSUE TITLE
Assert hit when using native file dialogs

### ISSUE THREAD

**Issue by mmyros** [open-ephys/GUI#142]
Saving config files results in crashes as described here http://www.juce.com/forum/topic/assert-hit-when-using-native-file-dialogs.

apt-get remove zenity fixes the problem. This issue should have been fixed if Juce past version 2.1.5, but aparrently it isn't.

This affects the master and spikesorting branch on my debian wheezy.

**Comment by FloFra** [comment]
This issue should be fixed with the merge and probably can be closed.
