### ISSUE TITLE
High CPU usage by other software can cause crashes

### ISSUE THREAD

**Issue by jsiegle** [open-ephys/GUI#143]
A user has reported crashes when using processor-intensive software on the same computer as the GUI. The obvious fix is to just run the GUI on its own, but it would be nice to have it respond gracefully (perhaps with a warning) rather than just crash.

This is likely to be caused by an AudioSampleBuffer assertion due to unprocessed buffer samples, but I'd have to replicate the error to be sure.

**Comment by jvoigts** [comment]
Added new issue/feature request to just add warnings for now: #304

**Comment by jsiegle** [comment]
Haven't seen this at all recently, including when running spike sorting in another process—this can slow the GUI down significantly, and is therefore not recommended, but it doesn't cause it to crash.
