### ISSUE TITLE
FilterNode.cpp function call inefficiency?

### ISSUE THREAD

**Issue by mnolan2** [open-ephys/GUI#145]
At the for loop (line 144 of FilterNode.cpp, my branch of the repo) the upper index bound is defined by the output of a function call that is congruently made not ten lines above at the head of the function. I'm not the best at C++, so this might be the way that things are done, but it seems like an inefficiency to me. Any thoughts?

**Comment by jsiegle** [comment]
As of GUI version 0.6.0, the Filter Node has been substantially refactored and now lives [here](https://github.com/open-ephys/plugin-GUI/tree/main/Plugins/FilterNode). If there still appear to inefficiencies in the implementation, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
