### ISSUE TITLE
Allow spike detection across more than 4 channels

### ISSUE THREAD

**Issue by jvoigts** [open-ephys/GUI#148]
We should allow spike detection across more than one tetrode. This would be very useful for many types of dense laminar probes.

Additionally, it would be nice to allow overlapping Ntrodes in the GUI, this should probably be taken care of in the next proper rewrite of the spike detector UI.

**Comment by jsiegle** [comment]
The GUI can still only detect spikes across a maximum of 4 channels. If you need more channels for your experiments, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
