### ISSUE TITLE
Fast settle TTL event issue

### ISSUE THREAD

**Issue by cjblack** [open-ephys/GUI#151]
I'm running the GUI on the spikesorting branch fine on OSX, but my TTL inputs are not shutting down the amps.  I'm registering events, but the amps are still online.  I also have the updated fast settle bit file - anyone else able to get this feature working on OSX?

**Comment by jsiegle** [comment]
The source code for the Rhythm Plugins (Acquisition Board and Intan RHD USB) now live here: https://github.com/open-ephys-plugins/rhythm-plugins

If you're still experiencing any problems with these plugins, please open a new issue in that repository.
