### ISSUE TITLE
Crash when reducing window size a lot

### ISSUE THREAD

**Issue by wonkoderverstaendige** [open-ephys/GUI#156]
Tested under Linux Mint/Ubuntu 14.04, the GUI v0.3.1 crashes with `JUCE Assertion failure in juce_ResizableWindow.cpp:237` when the height of the inner window is reduced to the size of the menu bar (i.e. getHeight() in [UIComponent.cpp](https://github.com/open-ephys/GUI/blob/master/Source/UI/UIComponent.cpp#L105) hits 0).

Looking at the code in [MainWindow.cpp](https://github.com/open-ephys/GUI/blob/master/Source/MainWindow.cpp#L71) at least the fact that the size constraint is not followed by the DocumentWindow is known (see also this [thread](http://www.juce.com/forum/topic/linux-setresizelimits) in the Juce forum).

**Comment by jsiegle** [comment]
The GUI now enforces a minimum window size.
