### ISSUE TITLE
(Spikesorting branch) Stopping Acquisition/Disabling Network Events freezes GUI

### ISSUE THREAD

**Issue by linussun** [open-ephys/GUI#157]
Running on Clean Ubuntu 12.04LTS install (running in a Xen VM).

I have compiled GUI with the latest libraries from zeromq-4.0.4 and google protocol buf 2.5.0.  When running GUI, when adding a Network Events Source, and pressing "Play" to start acquiring data, I am able to send basic text via ZeroMQ messaging (via port 5556) from my QNX6.4.0 PC that appears in the "Log" tab in GUI. However when pressing the "Play" button to stop acquisition, text output on the command line succesfully outputs STOP RECORDING, then a number of text items are output on the command line including "Disabling Bandpass Filter, Disabling LFP Viewer, Ending animation"

However the the text output stops at "Disabling Network Events" and then the entire GUI freezes and becomes unresponsive.  

If I do not use Network Events as a source, and only Rhythm FPGA, I am able to stop/start data acquisition just fine without GUI freezing. Thus this problem with freezing the GUI seems specific to the "Network Events" Source code. 

If I use "top" and look at the processes running, the open-ephys binary is still running with 2.3% cpu time and 6.2% memory while it is frozen.

I am able to compile the master source code (that doesn't have Network Events/Spikesorting code) and everything runs fine for acquisition from the Rhythm FPGA. Thanks.

**Comment by jsiegle** [comment]
This is now fixed.
