### ISSUE TITLE
[LFP Viewer] Scroll back

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#175]
One really useful feature for the LFP viewer would be to be able to scroll back (in time) when pausing the display. Keeping a buffer of 30-60 seconds would do it.

One a related note, in the current implementation of the pause ability, there is a small bug.
When paused, if you change the voltage range of spread, things rescale nicely. However, if you change the Timebase or Color grouping, things do not update. In particular, for the Timebase, the time scale displayed on top is changed, but not the actual signal.

**Comment by jsiegle** [comment]
This has not been implemented yet, due to the substantial overhead of keeping that much data in memory. If you need this feature for your experiments, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
