### ISSUE TITLE
Accelerometer/ADC sampling rate

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#176]
According to the datasheet, the Intan chip is acquiring data from the 3 aux channels with a quarter of the sampling rate than for the other channels. However, in the recorded data this is not taken into account and the SR is not registered somewhere. This could be a useful addition.

On a related note, what is the sampling rate for the 8 ADC input channels? Is it set to be the same as the one selected for the neural data? If not, maybe allowing the option to set it independently (and register this value) would be useful as well.

**Comment by jsiegle** [comment]
The sampling rate for all AUX and ADC channels should be the same as the neural data.
