### ISSUE TITLE
DSP offset  and filters

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#177]
In the Rhythm source module, there is the possibility of selecting the low and high bandwidth frequencies, set by default to 1Hz and 7500Hz. 
I could not find any documentation on that, but I suppose it corresponds to the frequency bandwidth that can be set at the Intan GUI software and is the amplifier bandwidth.
However, I am not able to set this value to less than 1Hz (for example 0.1 Hz).

Additionally, I could not find any option about the DSP offset removal employed by the Intan chip. Is this option enabled or disabled by default? Where and how can I enable/disable this function and set the desired cutoff frequency?

Looking at the RHD2000Thread.cpp, I see that there are the following values set:
dspEnabled(true),
desiredDspCutoffFreq(0.5f),
desiredUpperBandwidth(7500.0f),
desiredLowerBandwidth(1.0f),

If I understand correctly how this works, the DSP offset cutoff frequency, if enabled, is supposed to be a few times higher than the lower bandwidth value.

I think that adding a toggle button and dsp offset frequency text input would be a useful addition.

A minor issue: In some cases I was able to set the low bandwidth value to 0, but I could not reproduce it. In most instances I get a "Value out of range" message on the bottom.

**Comment by Aztla** [comment]
I have acquired data from an OpenEphys system and I realized I had some LowCutFilters at 2.3Hz and 2.5Hz, also some settings with the DSPOffset on and off. Could you let me know from what frequencies the signal is not dampened anymore and if it is possible to correct for the offset?
