### ISSUE TITLE
Data appears weird

### ISSUE THREAD

**Issue by PyTorr** [open-ephys/GUI#178]
I am using the  Open-Ephys with intan. When I am comparing the signal between Open-Ephys software and Intan's software, I don't get the same signal.

Someone has the same problem?

**Comment by jsiegle** [comment]
The LFP Viewer has been substantially updated, and this should no longer be an issue. If you have any recommendations for how to improve the LFP Viewer's data visualization, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
