### ISSUE TITLE
HDF5 C++  library missing

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#180]
With the new changes, the compiling broke for me on Mavericks with XCode 6.
1. The HDF5 C++  library is missing (H5Cpp.h not found)
2. I had to set the correct Base SDK in XCode project properties

I see in the code the dll's are included for VisualStudio so it might be only for Mac OS X the problem.

**Comment by vishalgupta84** [comment]
having the same problem : Compiling KwikFileSource.cpp
../../Source/Processors/FileReader/KwikFileSource.cpp:23:19: fatal error: H5Cpp.h: No such file or directory
 #include <H5Cpp.h>
                   ^
compilation terminated.
make: *** [build/intermediate/Debug/KwikFileSource_58456030.o] Error 1
  HDF5 library and include path's is /home/vsl/VSL/programme/HDF/HDF_Group/HDF5/1.8.16 in this directory .. somebody help me to fix this one
