### ISSUE TITLE
Networking branch issues thread

### ISSUE THREAD

**Issue by linussun** [open-ephys/GUI#185]
Starting a thread about the networking branch while testing it and getting it ready for experiments. At this point the present functionality is: 

Network source is available
When plugged into signal chain, network messages received will appear on command line as "Received Message!" even if "play" acquisition button is off. The actual messages will be printed in lower left hand corner of box.

Bugs encountered:

After network source is added to a signal chain, if you click on play, everything works fine, as soon as you click on the play button to turn off acquisition, GUI freezes after printing messages on command line: "Disabling Network Events"

GUI freezes on "Restart Connection" button in the Network Events Source. 

If there is a miscommunication (unclear how it happens at the moment) between the network source of ZeroMQ message strings, and GUI, both the sender and ZeroMQ will potentially freeze. I suspect this behavior may have to do with zmq_ctx_new and zmq_ctx_destroy commands on the sender side are not sent in the right order or there is an 'open looop' context that is not closed/destroyed, though I am not quite sure yet.

**Comment by jsiegle** [comment]
The Network Events plugin now lives here: https://github.com/open-ephys-plugins/network-events

If you're experiencing any issues with network messages, please open a new issue in that repository.
