### ISSUE TITLE
Not all channels saved

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#200]
There are some instances (has happened more than once, but I cannot reproduce it consistently), that whereas all channels are selected for saving, not all channels are saved but only the first headstage. 
I think it might have something to do with the selection of continuous vs per stream naming.
I do have an example recording (too big to upload), where only 32+3 aux channels were saved but in the settings file all channels are supposed to be saved.

**Comment by jsiegle** [comment]
Recording now happens exclusively through Record Nodes. This should no longer be an issue.
