### ISSUE TITLE
libHDF version is not in Ubuntu 14.04

### ISSUE THREAD

**Issue by ckemere** [open-ephys/GUI#203]
I want to spark a discussion point. I think we should avoid bleeding-edge libraries. Recording computers are typically connected to at least an internal internet, and so keeping them up-to-date security wise is critical. The use of non-repository libraries becomes a potential breakage point in future updates.

**Comment by jsiegle** [comment]
[OpenEphysHDF5Lib](https://github.com/open-ephys-plugins/OpenEphysHDF5Lib) now includes the necessary library files in the source code repository.
