### ISSUE TITLE
Case-sensitive include in KwikFileSource.cpp

### ISSUE THREAD

**Issue by AGenews** [open-ephys/GUI#204]
I just wanted to compile the GUI at my linux machine  3.16.0-25-generic #33-Ubuntu x86_64 14.10 and realized, that in /GUI/Source/Processors/FileReader/KwikFileSource.cpp line 23 I had to change #include h5cpp.h to #include H5Cpp.h.
By the way Ubuntu 14.10 comes with libhdf5-serial-dev version 1.8.12.

Best,
Andreas

**Comment by jsiegle** [comment]
The Kwik Format has now been deprecated.
