### ISSUE TITLE
Feature request: LFP viewer channel spacing

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#205]
If you have a large amplitude signal and you want to see it in detail, (i.e without changing the voltage scale), then each channel starts overlapping with the other.
It would be nice if there was a menu in the LFP viewer that modifies the spacing of the displayed channels.
This is different from the spread, which is just for the number of px devoted to each channel.

**Comment by jvoigts** [comment]
fixed in main repo testing, in the new lfpviewer beta plugin, see if that works for you and possibly add an issue/feature request there.
