### ISSUE TITLE
Feature request: Structured display location in LFP viewer

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#209]
It would be great if we can arrange the signals displayed in the LFP viewer with some structure (e.g. seeing the different shanks of a probe as different columns).
This role for now is (only partially) fulfilled by the color grouping.

**Comment by jsiegle** [comment]
This has not been implemented yet, although you can split the LFP Viewer vertically and scroll to different parts of the probe within each view. If you need this feature for your experiments, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
