### ISSUE TITLE
Feature request: Display color per channel selection

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#210]
A nice feature would be if you can click on each channel and get a pop-up palette to select the display color for that signal. It would give more flexibility compared to the currently existing color grouping (which is nice though so it would be good if the two features play together nicely).

**Comment by jsiegle** [comment]
This has not been implemented yet. If you need this feature for your experiments, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
