### ISSUE TITLE
Bug: GUI doesn't support 2 RHD2164 chips on same port.

### ISSUE THREAD

**Issue by abcas1990** [open-ephys/GUI#216]
The way the chips are connected are as the datasheet mentions here

![image](https://cloud.githubusercontent.com/assets/9813943/5081680/1af5fa90-6ea1-11e4-846a-1917f168f8b6.png)

The bug is coming from lines 557 to 563 in https://github.com/open-ephys/GUI/blob/master/Source/Processors/DataThreads/RHD2000Thread.cpp

It looks like one 64 channel chip is treated as 2*32 channel chips and takes both streams for some reason. The comment in the code mentioned that it should be changed. I wish I had the solution but I haven't dug into the whole repo yet.

**Comment by jsiegle** [comment]
This is now fixed. The GUI can record from up to 8 RHD2164 chips simultaneously.
