### ISSUE TITLE
Does LFP viewer have a channel number limit?

### ISSUE THREAD

**Issue by jialinzou** [open-ephys/GUI#217]
When I try to display 262 channels in LFP viewer, the GUI crashed. Following messages are what I received from console. Any idea of it? Thanks!

Adding audio callback.
Setting num inputs on LfpDisplayCanvas to 262
Setting displayBufferSize on LfpDisplayCanvas to 150000
Setting sample rate of LfpDisplayCanvas to 30000
Beginning animation.
JUCE Assertion failure in juce_AudioSampleBuffer.h:145

**Comment by jsiegle** [comment]
The LFP Viewer can now display a maximum of 10,000 channels per stream, and an unlimited number of streams.
