### ISSUE TITLE
RHD2164 recording not working properly

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#222]
When connecting a 64ch headstage it appears as 2x32 (this has been described before as a workaround).

However, channels 1-32 look ok, whereas channels 33-64 (some, not all channels), look messed up (artifacts - digital noise).

Also, 6 aux channels appear (this cannot be the case since there are no such channels for this chip).
Not all of these channels show signals, but some do (which is probably related to #207 ).

**Comment by ADuszk** [comment]
Hi, I'm having the same problem using RHD2164 with Intan acquisition board, channels 1-32 look fine but channels 33-64 have digital glitches.

The headstage appears correctly as one 64 channel in Rhythm FPGA. Is this a known bug?
