### ISSUE TITLE
LFPs are not filtered with low pass filter setting.

### ISSUE THREAD

**Issue by wehr-do** [open-ephys/GUI#226]
I'm using intan board and open-ephys gui. The problem is pretty random and I haven't noticed a pattern, but when I process LFP recordings, I find that they were not low pass filtered during the recording. All parameters appear to be set in the gui in bandpass filter module during the recordings. I use the same saved configuration every time.

**Comment by aacuevas** [comment]
Just fyi, I tried and it seems to both record and show filtered signals for me. Can you please attach a signal chain that causes this issue for you?

**Comment by jsiegle** [comment]
This should be fixed in the latest version of the GUI.
