### ISSUE TITLE
Time Base changes when reviewing kwik files in open ephys GUI

### ISSUE THREAD

**Issue by mikailweston** [open-ephys/GUI#233]
When replaying kwik data back in open ephys to save in open ephys format, the time in the bottom left corner (of original file) moves much more quickly than the recorded time in the top right hand corner, meaning that when re-recording a file of 20 mins, the open ephys file is only around 18 mins long.

**Comment by jsiegle** [comment]
This is fixed in the latest version of the File Reader (although the Kwik format is now deprecated).
