### ISSUE TITLE
Delete libhdf5_12 branch

### ISSUE THREAD

**Issue by ckemere** [open-ephys/GUI#234]
Can someone with the power to do so delete the "libhdf5_12" branch? I've re-done all the (libHDF) changes that are necessary to compile in Ubuntu 14.04 and the ubuntu_14.04 branch is now going to track the master branch.

**Comment by open-ephys** [comment]
Done. Is there any reason not to merge ubuntu_14.04 into master at this point?

**Comment by kemerelab** [comment]
I'd rather keep it as a tracking branch so that as other HDF 1.8.12 stuff gets added into master I can have a bit of latency before they have to be hacked into shape. I can shift it to my own github if you'd prefer.

**Comment by jsiegle** [comment]
No, it's fine to keep it here.
