### ISSUE TITLE
Spike Sorter

### ISSUE THREAD

**Issue by koreign** [open-ephys/GUI#236]
For people dealing with single unit analysis, the spike sorter module is the one which will convince people to switch from other system to open-ephys box + GUI. I have been experiencing some small problems using it (bug, usage and suggestions):

Bug:
once a tetrode is made, making a new box unit and add Box work perfectly. However, new polygon doesnt do anything and more importantly the button next/prev electrode do not change the hand over the other electrodes: in other words whatever I do all the box unit i make appear in the top left quadrant only. 

Usage:
Wouldn't it be more intuitive if the Spike Detector could record spike files rather than continuous signals since it was tuned for spike detection and even online unit hunting ? 

Suggestions:
1. why do i use the spike sorter more than the spike detector? simply everything is more visible there. The spike detector module return graphs that are too small to manipulate and to look at I think, in addition the arrangement of the windows is almost not possible (enlargement, zoom etc).
2. for both spike detector and spike sorter, adjusting the threshold using a scroll but also entering a number would be very beneficial (especially for people with muscle tremor "joke" ^^).
3. for the spike sorter: the pca plot is interesing but I still like to be able to identify the units using a 2D x-y plot of spike max amplitude. Both plots could be complementary i believe.
4. compared to the cheetah (neuralynx), the spike retriggering seems missing or is it already implemented but not accessible ?

I hope that my suggestions are not related to me misusing the GUI, rather I try to take an end-user point of view. Looking forward to help.

**Comment by shayo** [comment]
FYI: Polygon is edited in PCA space, not in wave-form space. It works for me:
![image](https://cloud.githubusercontent.com/assets/1977614/5670294/9b8453fe-974c-11e4-933c-c14a155c36f2.png)

**Comment by shayo** [comment]
I think you can delete it. But you need to highlight it first by single
clicking on it, then click on delete.

And the prev next was recently fixed as well (I can't remember on which
branch)

**Comment by koreign** [comment]
There is still one thing I can't acheive with the spoke sorter:
1. in order to correctly generate unit cluster, I should be able to generate the boxes within each of the quadrants (channels) of a tetrode for example.
2. When I push any button "new box unit" or "add box" it only generate boxes for the first channel.
3. how do you generate boxes in other channels ?

**Comment by fedecarne** [comment]
Hi! Has this been solved?

**Comment by jsiegle** [comment]
The Spike Sorter source code now lives here: https://github.com/open-ephys-plugins/spike-sorter

If you're having any issues with that plugin, please open a new issue in that repository.
