### ISSUE TITLE
yosemite master not working

### ISSUE THREAD

**Issue by rjs360** [open-ephys/GUI#245]
I installed the binary from the Open Ephys software page, copied the three .dylib files to the /usr/lib directory, but running the application file after this gives me an error on Mac OS 10.10.2;

"open-ephys cannot be opened because of a problem. 
Check with developer bla bla bla etc. "

This happens both on an iMac and a powerbook running 10.10.2.
Any thoughts on how to solve this?  Build from scratch?

**Comment by jsiegle** [comment]
Maybe try copying those files to /opt/local/lib instead? I'm not sure what else the problem could be.

Can you paste the exact error message?

**Comment by rjs360** [comment]
Hi Josh,

I built it from scratch using homebrew which, after installing hdf5 and 
the other file with macports, now works fine.

Then I tried installing the binary again, and it now works too...
must have been missing some files.

Ruud

> Josh Siegle <mailto:notifications@github.com>
> February 10, 2015 at 1:29 PM
>
> Maybe try copying those files to /opt/local/lib instead? I'm not sure 
> what else the problem could be.
>
> Can you paste the exact error message?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/open-ephys/GUI/issues/245#issuecomment-73754588>.
>

-- 
Ruud Schilder, Ph.D.
Assistant Professor of Entomology and Biology
Pennsylvania State University
rjs360@psu.edu
http://ento.psu.edu/directory/rjs360
http://www.personal.psu.edu/rjs360/

**Comment by koreign** [comment]
I also had the same problem in installing the binary. I think that the wiki should mention about installing macports, updating and installing the QMzero thingy no ?

**Comment by jsiegle** [comment]
Is MacPorts necessary, or can you get it to run by copying the .dylib files included in the downloaded directory?
