### ISSUE TITLE
USB disconnection crash

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#247]
If for some reason USB gets disconnected while the GUI is running (even when there is no acquisition taking place), the GUI crashes completely and in the terminal this message is printed ad infinitum

No such deviceerror usb control message: No such deviceerror usb control message: No such deviceerror usb control message:

There should be some error catching missing there.

**Comment by jsiegle** [comment]
The source code for the Rhythm Plugins (Acquisition Board and Intan RHD USB) now live here: https://github.com/open-ephys-plugins/rhythm-plugins

If you're still experiencing this problem, please open a new issue in that repository.
