### ISSUE TITLE
Channel map crash

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#251]
If you try to load the saved settings of a channel map that has different channel number than currently, the GUI crashes with segmentation fault (core dumped).

it is quite easy to reproduce: with one headstage, enable adc channels and save the channel map. This saves 32 + 3 + 8 channels.
Then restarting the GUI, if you do not enable adc (default), you have 35 channels. Trying to load the channel map, crashes the GUI. Maybe it should be checking if there is a mismatch and not loading the file with an error message if there is a problem.

**Comment by aacuevas** [comment]
Should be fixed now.
