### ISSUE TITLE
Settings xml saving

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#252]
in many cases, the settings.xml file is not being saved. However I could not figure out yet what causes this behavior.

**Comment by aacuevas** [comment]
Do you mean the auto saved settings or when manually saving a signal chain?

**Comment by nikolaskaralis** [comment]
The auto-saved settings.xml file that is supposed to be contained in each
recording directory.

On Thu, Feb 19, 2015 at 10:09 AM, Aarón Cuevas López <
notifications@github.com> wrote:

> Do you mean the auto saved settings or when manually saving a signal chain?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-ephys/GUI/issues/252#issuecomment-75018551>.
>



-- 
Nikolas Karalis - http://www.nikolaskaralis.gr <http://nikolaskaralis.gr>

*Neuroscience Graduate Student*
Ludwig-Maximilians Universität München
Centre for Integrative Neuroscience -  Universität Tübingen
*Neuroscience Graduate*
Université Bordeaux 2 - Charité Universitätsmedizin Berlin
*Applied Mathematics and Physics Graduate*
National Technical University of Athens, Greece

**Comment by aacuevas** [comment]
I can't reproduce this, at least on Windows. If you find a way to provoke this issue please tell me.
I have, however, fixed a related issue: we were generating a settings file for only the first "experiment" (acquisition) per folder, even if the chain was changed. I've fixed that so, perhaps, that also fixes this. Please check it if you can.

**Comment by nikolaskaralis** [comment]
I don't have a particular way to check it (not sure when exactly it was happening) however lately when recording the settings.xml appears normally so we can consider it fixed for the moment.
