### ISSUE TITLE
Ecube support

### ISSUE THREAD

**Issue by shayo** [open-ephys/GUI#254]
FYI, the ECUBE_COMPILE is (still?) defined in VS2013 and causes compilation errors (specifically, on
#import "libid:60C0AAC2-1E0B-4FE5-A921-AF9CEEAAA582")

**Comment by mborisov1** [comment]
Is this a problem? It's just that I always compile OpenEphys with ECube support and therefore I define that flag. The #import directive will not produce errors if you install EcubeAPI.

If you think it's a problem, I could deactivate the ECUBE_COMPILE flag before committing the .vcproj file to the repository.

**Comment by shayo** [comment]
Just a thought. Most users out there don't have the Ecube, and it doesn't
say anywhere you need to install the API to compile the project.
I would recommend to either install the eCube API by default, or to set
that flag to zero by default.


On Wed, Feb 18, 2015 at 9:59 AM, mborisov1 <notifications@github.com> wrote:

> Is this a problem? It's just that I always compile OpenEphys with ECube
> support and therefore I define that flag. The #import directive will not
> produce errors if you install EcubeAPI.
>
> If you think it's a problem, I could deactivate the ECUBE_COMPILE flag
> before committing the .vcproj file to the repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-ephys/GUI/issues/254#issuecomment-74877328>.
>



-- 
Shay Ohayon
HHMI Postdoc Fellow of the Life Sciences Research Foundation
DiCarlo's lab, MIT, 46-6147
+1 617-324-3593

**Comment by mikailweston** [comment]
I agree, I recently had the problem that I was unable to compile using
VS2013 as I had not updated the eCube API and uninstalled the previous
version.

If the API will be updated frequently it may be better to deactivate the
compile flag and put instructions in the readme for how to install the
eCube API and reactivate the compile flag.

**Comment by mborisov1** [comment]
Ok, I'll deactivate the ECUBE_COMPILE flag in the project file the next time I'm going to commit to the repository.

**Comment by mborisov1** [comment]
Seems that the ECUBE_COMPILE flag is gone from the VS2013 project file(s). I'm not going to commit the project files with this option set anymore.
