### ISSUE TITLE
LFP viewer display bug

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#259]
When recording for ~2 hours, the display of the LFP viewer starts looking weird for some of the channels (it starts with channel 1 and as time passes, it starts happening for channel 2 etc).
The signal starts looking interrupted, however looking at the recorded data, everything looks fine.
Stopping the acquisition and starting again fixes this issue.

**Comment by aacuevas** [comment]
This might be tricky to check, but it probably stems from some mismatch at some buffer, I'll look at them. In the meanwhile, if it happens to you again, could you please attach a screenshot to see what it looks like?

**Comment by nikolaskaralis** [comment]
Will do.
However it happens invariably every time after little less than 2 hours of
recording.
From what I have noticed, it doesn't happen during acquisition, no matter
how long it is, but only during recording.

On Wed, Mar 4, 2015 at 6:40 PM, Aarón Cuevas López <notifications@github.com
> wrote:

> This might be tricky to check, but it probably stems from some mismatch at
> some buffer, I'll look at them. In the meanwhile, if it happens to you
> again, could you please attach a screenshot to see what it looks like?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-ephys/GUI/issues/259#issuecomment-77206317>.
>



-- 
Nikolas Karalis - http://www.nikolaskaralis.gr <http://nikolaskaralis.gr>

*Neuroscience Graduate Student*
Ludwig-Maximilians Universität München
Centre for Integrative Neuroscience -  Universität Tübingen
*Neuroscience Graduate*
Université Bordeaux 2 - Charité Universitätsmedizin Berlin
*Applied Mathematics and Physics Graduate*
National Technical University of Athens, Greece

**Comment by aacuevas** [comment]
Which recording format are you using? Have you checked if it happens with both? Perhaps there is something there that is lagging the GUI when the files get big enough.

**Comment by nikolaskaralis** [comment]
I am recording with the OpenEphys format. Never tried with the Kwik one.

One thing that I noticed after the initial post: If I scroll vertically the
LFP viewer it temporarily displays everything in the signal, but then
immediately reverts back to the broken view.

Until I provide the screenshot: The broken view looks as if it was plotted
with dashed line instead of continuous line. And it is not on all the
traces, but only some of the channels (starting from the first).

On Wed, Mar 4, 2015 at 8:41 PM, Aarón Cuevas López <notifications@github.com
> wrote:

> Which recording format are you using? Have you checked if it happens with
> both? Perhaps there is something there that is lagging the GUI when the
> files get big enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-ephys/GUI/issues/259#issuecomment-77230654>.
>



-- 
Nikolas Karalis - http://www.nikolaskaralis.gr <http://nikolaskaralis.gr>

*Neuroscience Graduate Student*
Ludwig-Maximilians Universität München
Centre for Integrative Neuroscience -  Universität Tübingen
*Neuroscience Graduate*
Université Bordeaux 2 - Charité Universitätsmedizin Berlin
*Applied Mathematics and Physics Graduate*
National Technical University of Athens, Greece

**Comment by nikolaskaralis** [comment]
It seems it is happen during just acquisition as well (not only during recording).

**Comment by nikolaskaralis** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/4306518/6532099/4973ddc2-c43e-11e4-8ae8-4b336c033a1c.png)

**Comment by jsiegle** [comment]
Thanks for posting that! I've seen something similar as well. Its likely caused by a drift in display buffer alignment over time. So it's a display bug, not something wrong with the underlying data. Aarón, can you add a check to make sure this doesn't happen?

**Comment by aacuevas** [comment]
I've seen something like that when mixing different sources, but it is weird to have alignment issues when everything comes from the same place at the same pace. I'll take a good look at the buffers, there must be something amiss there.

**Comment by nikolaskaralis** [comment]
As I wrote above, it happens even with a 16ch headstage, and invariably at
some time after ~1h of recording.

On Fri, Mar 6, 2015 at 8:43 PM, Aarón Cuevas López <notifications@github.com
> wrote:

> I've seen something like that when mixing different sources, but it is
> weird to have alignment issues when everything comes from the same place at
> the same pace. I'll take a good look at the buffers, there must be
> something amiss there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-ephys/GUI/issues/259#issuecomment-77622635>.
>



-- 
Nikolas Karalis - http://www.nikolaskaralis.gr <http://nikolaskaralis.gr>

*Neuroscience Graduate Student*
Ludwig-Maximilians Universität München
Centre for Integrative Neuroscience -  Universität Tübingen
*Neuroscience Graduate*
Université Bordeaux 2 - Charité Universitätsmedizin Berlin
*Applied Mathematics and Physics Graduate*
National Technical University of Athens, Greece

**Comment by aacuevas** [comment]
I've added a mutex to prevent different threads writing to the buffer indexes. I've had the GUI running for 2h and didn't get that. There were occasional gaps in all channels (missed paint calls due to timing) but nothing so endemic. Does it get better for you?

**Comment by nikolaskaralis** [comment]
It seems this fixed it.  I recorded for ~5h and there was no such issue.
