### ISSUE TITLE
Consider using HDF for data storage

### ISSUE THREAD

**Issue by ckemere** [open-ephys/GUI#26]
The Pandora project is promoting an HDF format for electrophys data. We should consider adopting it?

https://github.com/G-Node/pandora/wiki

**Comment by FloFra** [comment]
They seem to be in beta now after multiple rounds of discussions with people from Janelia and SFN:
   https://github.com/G-Node/nix

How are the plans to integrate it?

**Comment by jsiegle** [comment]
The GUI now supports writing directly to HDF5 files, via the [OpenEphysHDF5Lib](https://github.com/open-ephys-plugins/openephyshdf5lib)
