### ISSUE TITLE
Channel Map recording flag

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#261]
The channels selected for recording are switching on and off randomly from time to time (acquisition start/stop or adding new modules in the pipeline). I don't have a specific situation to reproduce it though.

**Comment by aacuevas** [comment]
When this happens, do all the channels switch off or only some of them?

**Comment by nikolaskaralis** [comment]
Usually only some of them (can be different number of channels and subset).
This happens quite often (almost every time I am loading/editing the
pipeline) and has resulted many times in recording wrong/less channels.

On Wed, Mar 4, 2015 at 6:43 PM, Aarón Cuevas López <notifications@github.com
> wrote:

> When this happens, do all the channels switch off or only some of them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-ephys/GUI/issues/261#issuecomment-77207085>.
>



-- 
Nikolas Karalis - http://www.nikolaskaralis.gr <http://nikolaskaralis.gr>

*Neuroscience Graduate Student*
Ludwig-Maximilians Universität München
Centre for Integrative Neuroscience -  Universität Tübingen
*Neuroscience Graduate*
Université Bordeaux 2 - Charité Universitätsmedizin Berlin
*Applied Mathematics and Physics Graduate*
National Technical University of Athens, Greece

**Comment by aacuevas** [comment]
Should be fixed now, please check if it works now for you.
