### ISSUE TITLE
Shift in referencing in Channel Map after disabling Channels

### ISSUE THREAD

**Issue by koreign** [open-ephys/GUI#278]
I believe there is still a problem in the channel mapping ( I install the binary for windows 32 - 0.3.5).

The problem:
- on a simple chain: fpga-channel map- lfp viewer + intan 16ch (fpga set to 32 channel)
- naturally: chan 1-8 and chan 25-35 are empty
- so ones usually disable those channels
- once disabled: if one set bank "A" using channels 9 to 12 and 9 for reference, then 9 will not become 0. None of the channel is actually going to 0 for any channel of that bank. After playing around with all the channels I found that the references are all shifted somehow:
ref -> chan going to 0
17 -> 9
18 ->10
19 ->11
20 ->12
... 24 ->16, however reference is found for 17 to 24 (because they have been shifted to 25, 26 etc).

It should be a simple fix but very disturbing if gone under the radar. (that result is independent of the bank)

If no channel is disabled (original channel map module), then the referencing works fine.

**Comment by aacuevas** [comment]
Fixed, it was an indexing issue, seems to be working properly now.
