### ISSUE TITLE
Pulse Pal sink broken

### ISSUE THREAD

**Issue by nikolaskaralis** [open-ephys/GUI#282]
When dropping the PulsePal module to the chain, the GUI crashes.

**Comment by aacuevas** [comment]
I can't reproduce this on my development computer, but confirmed on my laptop. It's most probably caused by some serial port configuration, I'll look at that.

**Comment by jsiegle** [comment]
The Pulse Pal plugin now lives here: https://github.com/open-ephys-plugins/pulse-pal-output

If you're experiencing any problems with that plugin, please open an issue in that repository.
