### ISSUE TITLE
Implementing / integrating video tracking

### ISSUE THREAD

**Issue by rhayman** [open-ephys/GUI#297]
I've seen mention in various places of integrating videography into OE but looking around this doesn't appear to be a huge priority. It's something I would really like to see happen and I'm ready, willing and partially able to spend some time helping out with. Can anyone, a) point me in the right direction i.e. what the major obstacles might be in terms of hardware/ software and / or, b) discuss how they've managed to get video tracking working. I have a lot of chronic in vivo e.phys experience, lots of Matlab/ Python and am currently learning C/C++. Currently I'm working with Linux so platform-specific solutions (i.e. Bonsai) aren't really that useful.

**Comment by mmyros** [comment]
I like the Kinect camera and openv and simplecv. Take a look at my oram repo - the code is a mess but you may be able to find something useful. Network time stamps can be used with OE.
