### ISSUE TITLE
Segfault after removing last channel from spike sorter

### ISSUE THREAD

**Issue by simonster** [open-ephys/GUI#301]
Steps to reproduce:
1. Drag a source and the spike sorter to the bottom
2. Click the + button within the spike sorter and select a type of electrode
3. Click the - button within the spike sorter

[gdb output with backtrace](https://gist.github.com/simonster/8bbca921afb9eaf65a42)

**Comment by aacuevas** [comment]
Should be fixed now, it was a simple check.
