### ISSUE TITLE
Assertion failure on TTL input from Pulse Pal

### ISSUE THREAD

**Issue by lepmik** [open-ephys/GUI#310]
Hi,

I get a crash when sending a a burst of pulses to the TTL input but not when I stream the pulses to the Analog input.

``` Bash
Adding audio callback. # Starting acquisition is fine, but after some tens of pulses I get
JUCE Assertion failure in juce_AudioSampleBuffer.cpp:531 # The LFP display freezes but GUI works

Removing audio callback. # After pressing the play button to stop acquisition the GUI freezes totally
```

**Comment by open-ephys** [comment]
What's the frequency of the pulses?

**Comment by lepmik** [comment]
It's a 20 Hz pulse train on/off for one sec

**Comment by open-ephys** [comment]
Does it happen every time you send the pulses, or just occasionally? Also, which processors are in your signal chain?

**Comment by lepmik** [comment]
It happens every time, mostly after the first pulse train. 
Signal chain:
A: Rhythm FPGA > LFP Viewer with only the ADC's on
B: Serial Port > Pulse Pal

**Comment by open-ephys** [comment]
Can you try it with a headstage connected? There could be an issue with assigning timestamps to the pulses (which are converted to TTL events as soon as they arrive) when there's no headstage data. This is definitely something we can fix, using a headstage might solve the problem for now.

**Comment by lepmik** [comment]
Sorry for the delay. Connecting a headstage does make it more stable,
however I still get the same crash after sending several trains.

2015-09-02 20:48 GMT+02:00 open-ephys <notifications@github.com>:

> Can you try it with a headstage connected? There could be an issue with
> assigning timestamps to the pulses (which are converted to TTL events as
> soon as they arrive) when there's no headstage data. This is definitely
> something we can fix, using a headstage might solve the problem for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-ephys/GUI/issues/310#issuecomment-137207361>.
>



-- 
Mikkel Elle Lepperød <http://cinpla.org/people/>
Centre for Integrative Neuroplasticity (CINPLA <http://cinpla.org>)
University of Oslo (UiO <http://uio.no>)
Kristine Bonnevies hus, room 2513

**Comment by lepmik** [comment]
Hi, have you been able to look into this yet?

**Comment by jsiegle** [comment]
The Pulse Pal plugin source code now lives here: https://github.com/open-ephys-plugins/pulse-pal-output

If you're still experiencing any problems with this plugin, please open a new issue there.
