### ISSUE TITLE
Behavioral Video (Synchronous or at least known-time acquisition)

### ISSUE THREAD

**Issue by ckemere** [open-ephys/GUI#32]
Cross platform is particularly challenging, but it would be nice to include some basic stuff. In linux V4L has a great framework for simple analog capture cards. Additionally, there are a variety of webcams that appear to be reasonably cross platform, and Point Grey has some lower-cost scientific acquisition cameras that are fully cross platform.

A key feature would be integrating the frame times into the data record somehow

**Comment by jsiegle** [comment]
The recommended way to synchronize ephys data with with behavioral videos is to acquire the video with another application (e.g. Bonsai) and send the frame trigger times to the Open Ephys acquisition board (or other data source acquired by the Open Ephys GUI).
