### ISSUE TITLE
PARAM tab use on CAR module

### ISSUE THREAD

**Issue by vncntprvst** [open-ephys/GUI#332]
Hi all,
the parameters tab in the Common average referencing (CAR) module doesn't seem to be doing anything. The CAR module apparently always uses all incoming channels as input. An obvious use for parameters would be to enable selecting source channels for CAR (or, conversely, CAR target channels, but that'd be less interesting). 
Thanks,
Vincent

**Comment by sept-en** [comment]
Hello!

I've just fixed it and added some more functionality to the CAR plugin.
Now we can select any reference (input) and affected (output) channels.

Here's a brief list of changes:
 -    CAR processor: added feature to use custom reference and affected channels combinations;
-     Implemented ButtonGroupManager component, MaterialButtonLookAndFeel which are generic and will be useful for easier plugin creation later;
-     Added custom audio processor editor for CAR plugin - CAREditor;
-     Some minor changes in GenericEditor class which provide more possibilities for plugins (e.g. plugins can implement their own resized() methods, etc.);
-     Fixed default value wasn't set in the gain Parameter after creation;
-     Updated fonts.

You can also take a look at the related merged pull request, if you want:
https://github.com/open-ephys/plugin-GUI/pull/14
https://github.com/open-ephys/plugin-GUI/pull/15

Best regards,
Kirill Abramov.
