### ISSUE TITLE
Rhythm FPGA - audio output channels are incorrect

### ISSUE THREAD

**Issue by guangxingli** [open-ephys/GUI#336]
When a channel is selected on Rhythm FPGA "PARAM" tab, signal from another channel will be sent out from the audio output.
If a 32-channel headstage is connected to FPGA. For channels 1 to 31 on "PARAM" tab, the actual channel which will be sent out from the audio output is actually the next channel. For example, if channel-5 is selected, the signal from channel-6 will be sent out. Due to this, the signal from channel-1 is not possible to get from the audio output.

**Comment by aacuevas** [comment]
Oh, it's a simple indexing bug on channel selector. I need to be double check fixing it wouldn't affect other plugins (in which we may have "patched" it processor-side) before commiting.
