### ISSUE TITLE
Add UTC timestamp to each group in the kwik format

### ISSUE THREAD

**Issue by kylerbrown** [open-ephys/GUI#337]
I'd like to be able to tell when a recording happened. The filename itself does store when the first group was recorded, but not for subsequent groups in the same file. Having an hdf5 attribute with the UTC time would be valuable to me.

**Comment by jsiegle** [comment]
The GUI now saves a software timestamp (milliseconds since midnight Jan 1st 1970 UTC) at the start of each recording.
