### ISSUE TITLE
adding collapse sidebar for GUI 

### ISSUE THREAD

**Issue by humanwhoexplores** [open-ephys/GUI#338]
in the gui we must have a collapse sidebar to modify the width of processor section, this will allow us to free some real estate for tabs while still keeping some space for processors, or conversely allow us to increase the width of the processor section
currently if you want to free the space occupied by processor section you need to click on processor button which hides the processor list, and allots the space freed to tabs, i believe adding this functionality will be useful and will give more freedom to users to manage different sections on screen,

**Comment by jsiegle** [comment]
Are you referring to the processor list on the left of the main window? I'm not sure if the additional flexibility is needed here. Typically, the processor list is only open while the user is building the signal chain, and it can be closed while running the experiment. Dragging to make the list narrower is extra work that won't save much space.
