### ISSUE TITLE
Stable version for OSX 10.11?

### ISSUE THREAD

**Issue by macstry** [open-ephys/GUI#339]
I know development has halted for this GUI, but I seem to be currently caught between versions- the master on pluggin-GUI does not yet have any of the other pluggins enabled (when I built it, no LFP viewer or other sink), and I was not able to build this one due to an hdf5 library being missing. Any suggestions for how I could get a working GUI on 10.11?

Thanks

**Comment by jvoigts** [comment]
You have to separately build the plugins with 'make -f Makefile.plugins'.

If this doesn't solve it, see if the steps in the documentation work for you: https://open-ephys.atlassian.net/wiki/display/OEW/Mac+OS+X
