### ISSUE TITLE
PSTH needs to be plugin, bug report and Feature Request: trial by trial rasters

### ISSUE THREAD

**Issue by linussun** [open-ephys/GUI#340]
Hi, a couple of us in the Google Groups noted that Shay's PSTH sink has not been updated to the plugin architecture yet.  

Bugs noted in the PSTH module in 0.3.6 version of GUI:
1. Adjusting visualization menu time range before and after sync event crashes GUI, so there is only a default of a few hundred ms before and after a sync event. 
2. Any strings (I am sending strings with numerals/numbers as event codes) sent to the Network Source that is merged into PSTH sink crashes GUI. 
3. Sometimes the TTL input does not refresh the PSTH, unless the PSTH is cycled through raster mode turned on and then off.

FEATURES that would be nice for PSTH to be more useful:
(1) It would be nice to have PSTH's / histograms simultaneously plotted with actual rasters on a trial by trial  basis. This should be possible since up to the last 200 trials are remembered from the Source code.  
(2) The resolution of the PSTH histogram seems rather coarse, it looks binned over 20-50 millisecond time bins, is it possible to change this? I've attached an example raster diagram that is produced in REX (NIH sensorimotor labs) which allows for rasters to be updated and synchronized to an event code, additional event codes are marked on those single trial rasters, and panels of rasters are organized by trial type event codes. 

![rexdemoraster](https://cloud.githubusercontent.com/assets/6187350/15201421/c59094de-17be-11e6-9610-fe113554fb23.png)

(3) PSTH module to synchronize to more than one condition for example a network event code for a trial type and THEN synchronize the raster to a ttl pulse/photodiode pulse, this will allow for multiple rasters based on trial types with accurate and high temporal resolutions. 

Incorporating these features would make GUI fully fledged for acute experiments! I am happy to test and report back, and contribute where possible. 

Thanks,
Linus

**Comment by jsiegle** [comment]
The PSTH plugin has been substantially refactored and now lives here: https://github.com/open-ephys-plugins/online-psth

If you have any feature requests related to the latest version, please post an issue in that repository.
