### ISSUE TITLE
Windows version not able to produce LFP sin wave

### ISSUE THREAD

**Issue by atheliarosapaulli** [open-ephys/GUI#343]
I am currently working with the Open Ephys Windows GUI, and am unable to get the Windows version to display the characteristic LFP sin wave. I have been using the Plexon Headstage Tester Unit, in combination with the 1 minute long Test Spike and FP data sound clip (http://www.plexon.com/sites/default/files/TestSpike&FPdata-1min.wav). I have attached a picture of what I have been getting in the Windows GUI. The issue is reproducible, and I have also used the same equipment and sound file on both Linux and Mac system, and have been able to get the sin wave, so the problem seems to be unique to the Windows GUI.  

![open ephys on windows- unable to get sin wave from lfp](https://cloud.githubusercontent.com/assets/10857976/17792193/749507f2-656d-11e6-8a39-e61fbaef6492.PNG)

**Comment by jsiegle** [comment]
Are you using Windows 10? The Opal Kelly driver that we use to communicate with the acquisition board isn't guaranteed to work 10, so that could be the source of the issue.

Also, can you check and see if the recorded data look similar to what's displayed in the LFP Viewer?
