### ISSUE TITLE
KWD file reader amplitude

### ISSUE THREAD

**Issue by qqspm** [open-ephys/GUI#348]
Hi,
I have some problem to use the file reader for KWD files. 
It seems the amplitude of the signal are way bigger than it supposely to be. 5-10 x bigger?
Is there any solution?
Thanks,
Qiang

**Comment by Aleman-Z** [comment]
I reckon you need to multiply by a factor 0.195.

**Comment by aacuevas** [comment]
There is a bug that makes the read not parse correctly the scaling factor of kwd files made with the GUI itself. It is fixed in the testing and development branches and will be in the next release, which will be out soon.
