### ISSUE TITLE
About File Reader module

### ISSUE THREAD

**Issue by sergehijo** [open-ephys/GUI#351]
Hi all!!

I am currently testing the Pulse Pal module (and the configuration i made), so for that i need to read from a file before testing in it in an animal model (hence becoming the source and not needing a previous file). The thing is that reading from the wiki, only .kwd files can be open with this module. I tried all four files from the DataFiles directory (executable download) but these files can't be open, the message is "File type not supported".

Any solutions?

Link of the wiki: https://open-ephys.atlassian.net/wiki/sp...ile+Reader

BR-

Sergio

**Comment by jsiegle** [comment]
The Pulse Pal plugin source code now lives here: https://github.com/open-ephys-plugins/pulse-pal-output

If you're experiencing any problems with the latest version of the plugin, please open an issue in that repository.
