### ISSUE TITLE
Error during running

### ISSUE THREAD

**Issue by yannunh** [open-ephys/GUI#356]
![image](https://user-images.githubusercontent.com/39725910/40871015-f2b49f04-666e-11e8-91e2-4245fe791d85.png)

Hi, I got in trouble.

I use amp board Intan rhd2000 - RHD2216.
I tried to use acquisition board as recording neural data. (spike and LFP) 

So I set like this
![image](https://user-images.githubusercontent.com/39725910/40871057-8af7c3fe-666f-11e8-8214-42dc92710ffb.png)
![image](https://user-images.githubusercontent.com/39725910/40871063-962c88e0-666f-11e8-8a3f-65b76ad54186.png)
![image](https://user-images.githubusercontent.com/39725910/40871094-06a21a4a-6670-11e8-830b-38417e6b249d.png)
![image](https://user-images.githubusercontent.com/39725910/40871095-0c43a234-6670-11e8-969a-ef514ca3d57a.png)

I tried to start acquisition or record ( triangle and circle button above the left), and got error massage.

![image](https://user-images.githubusercontent.com/39725910/40871081-d5c6e784-666f-11e8-8cfe-cd94ac46b5c5.png)

this is when I click "debug(D)"
![image](https://user-images.githubusercontent.com/39725910/40871036-3c7f744c-666f-11e8-9602-baf4f7e1c668.png)
 

( The option channel 32 , it works )

**Comment by jsiegle** [comment]
Can you try reducing the number of stereotrodes to 8? It might be crashing because you have too many channels configured in the Spike Detector.
