### ISSUE TITLE
Multiple ADC boards not visible in LFP viewer

### ISSUE THREAD

**Issue by kimpossible11** [open-ephys/GUI#363]
Hello, I have a digital in, as well as an analog in, ADC board plugged into the OE board. If I select the ADC1-8 button in rhythm fpga module, I can then see the adc channels in the lfp viewer. However, if I plug in more than one board, I still only see 8 channels in the LFP viewer. Is it possible to view all 16 input channels in the LFP viewer?

**Comment by jsiegle** [comment]
The maximum number of analog input channels is 8. The other HDMI ports are for 8 channels each of analog output, digital output, and digital input.

The GUI is not aware of which HDMI ports have cables plugged in—whether or not it reads the ADC inputs just depends on whether or not you've clicked the button in the Rhythm FPGA module.
