### ISSUE TITLE
GUI should support drag and drop of an XML for Signal Chain

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [open-ephys/GUI#366]
Currently one needs to do Command + O or File > Open to load saved Signal Chain configurations from an .xml file. I think it would make a lot of sense if GUI supports drag and drop of an .xml file for signal chain. 

Also, the file chooser dialog by File > Menu shows all the file types, though is only accepts .xml files. This behaviour should be improved.

I hope you like these suggestions.

Best,
Kouichi

**Comment by jsiegle** [comment]
This has not been implemented yet. If you need this feature for your experiments, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
