### ISSUE TITLE
Is there a way to save the look of LFP viewer?

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [open-ephys/GUI#367]
I noticed that, while you can customize the look of LFP viewer, the XML file saved from FIle > Save does not store information about these parameters.

Is there a way to store the look of LFP viewer?

If not, don't you consider support for that?

Just like CHANNEL MAP, you can think of placing buttons for saving and loading a JSON file as well as extending the XML saved from File > Save to include the parameters here too.

**Comment by jsiegle** [comment]
All LFP Viewer parameters are now stored in the XML settings files.
