### ISSUE TITLE
LFP viewer ADC channels not displayed to scale

### ISSUE THREAD

**Issue by kimpossible11** [open-ephys/GUI#369]
Hello, 
I'm recording an analog signal off an ADC channel and I'm getting a weird scaling in the LFP viewer. Basically, if I put in a 500mV signal AC signal from a signal generator (with the default -5V/5V setting on the I/O board, and the default -5V/5V setting in FPGA setttings), it appears as a 4V signal in the LFP viewer (seen in the attached image at 2V range). However, both in the recorded file (OE file type) as well as on an oscillosope, the correct 500mV signal appears. The attached matlab plot y axis is in Volts (~0.5 V). Is this a quirk of the viewer or am I missing something?

![OE2Vscale](https://user-images.githubusercontent.com/22033569/60895632-e5f15480-a25c-11e9-8457-4ab667320e55.png)
![500mVSigGen2IOboard](https://user-images.githubusercontent.com/22033569/60895639-e8ec4500-a25c-11e9-8827-4ec13fdeee42.jpg)

**Comment by chentao-CQU** [comment]
Hello, I am also using open ephys this device, I am now experiencing a problem, when I build a signal chain and start collecting signals, 8 ADC channels start to display rectangular pulses, no matter if I connect the I/O  board ,it's always like this, which means that the analog signal is not input to the acquisition board at all. I want to know how to get the acquisition board to receive the analog input and display it on the GUI as shown in your figure.

**Comment by jsiegle** [comment]
If you're still experiencing this problem in the latest version of the GUI, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
