### ISSUE TITLE
40-samples Waveform

### ISSUE THREAD

**Issue by francescovaccari** [open-ephys/GUI#371]
Hi,
I am opening the .spikes files saved by the GUI in MATLAB and then converting the to .NEV files to perform offline spike sorting with the Plexon Offline Sorter. 
The Plexon sorter accepts 48-samples waveforms and it works bad with the 40-samples waveforms recorded in the .files (maybe they have some bugs ...).
How can I get 48-samples waveforms in my .spikes files by GUI ?
Thank you in advance

**Comment by jsiegle** [comment]
The 40-sample default spike width is set [here](https://github.com/open-ephys/plugin-GUI/blob/e922f25f5e09b83cd2c39de7394f35a9ea1ec19d/Source/Plugins/BasicSpikeDisplay/SpikeDetector/SpikeDetector.cpp#L162-L163). If you re-compile the GUI yourself, you could change these values.

However, if you already have the data in Matlab, can you just add 8 zeros to the beginning or end of the waveform before converting to .NEV format?
