### ISSUE TITLE
 Board Detection and LFP Signal Issues on Acquisition Board 

### ISSUE THREAD

**Issue by jesse-gilmer** [open-ephys/GUI#373]
Hello,
I have been having issues connecting the GUI to the acquisition board, and well as in detecting LFP signals.
I will usually get this error message:
![no-opal-error-openephys](https://user-images.githubusercontent.com/58186876/69566712-f50b4180-0f74-11ea-9fc8-04d792acded6.png)
but this can be temporarily resolved by cycling the board power via unplugging, at which point the board will connect, but the LFP will quickly grow until it becomes candy cane-like: 
![candy-cane-error-openephys](https://user-images.githubusercontent.com/58186876/69566774-14a26a00-0f75-11ea-90e8-75a086acbea3.png)
with the following error:
![header-error-openephys](https://user-images.githubusercontent.com/58186876/69566781-19ffb480-0f75-11ea-853e-5490201b6433.png)

I have recreated the board detection error on windows 7 pro and ubuntu 16.04. I have downloaded VS2012 and 2013, but that did not resolve the issue. The usb port does not make a difference. The board will show purple LEDs post-failure on the IO ports, the intan ports seem normal. 
Any help would be appreciated.
Best,
Jesse Gilmer

**Comment by aacuevas** [comment]
This seems like a hardware issue. Does the opal kelly appear on Windows' device manager?
Is it an usb2 or usb3 board?

**Comment by jesse-gilmer** [comment]
@aacuevas Initially it doesn't appear on the device manager (and also doesn't light up), but after being loaded into the GUI it appears as "FX3 Bootloader." This is a USB3 board.

**Comment by aacuevas** [comment]
Can you please send me to aaron (at) open-ephys.org the full console contents on a time when the device is detected by the GUI?
Could you also check if at that time the board appears in the device manager under FrontPAnel devices as XEM6310 ?

It might be a hardware issue, but I would like to confirm my suspicions.
