### ISSUE TITLE
Issue with saving a signal chain: one channel ignored

### ISSUE THREAD

**Issue by slizmg** [open-ephys/GUI#374]
Hi, 
In our lab we have encountered one problem when manually saving the settings (saving a signal chain): when opening a signal chain there is **one channel for which the internal settings of some modules are never saved** (spike detector, spike sorter). For every session, we have to manually write down the settings (thresholds) to prepare for the next recording session.

We have tried creating and saving new signal chains and using previous versions of GUI but we keep having the same issue with this specific channel. Do you know what could be causing this problem? 

We are working on windows, and GUI version v0.5.1, intan RHD2132 32. 

Thank you!

**Comment by jsiegle** [comment]
This should be fixed now. If you're still experiencing this problem in the latest version of the GUI, please open a new issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
