### ISSUE TITLE
v0.5.3 crashing while launching

### ISSUE THREAD

**Issue by shirquinn** [open-ephys/GUI#383]
Hi
Iv'e used the new version once and it worked fine, ever since, when i launch the gui it crashes instantly when trying to load parameters for rhythm pfga. what can be causing this?
thank you

**Comment by jtmiles** [comment]
I'm having the same issue as @shirquinn. Had a couple successful recording sessions but the GUI started crashing after trying to add an ADC channel with signals from a camera. Not sure where I can access the Rhythm FPGA parameters to take a look at them, either. Any advice would be great!

**Comment by jtmiles** [comment]
Ah, just found this comment to a similar sounding issue (open-ephys/plugin-GUI#402) in the updated repository

**Comment by shirquinn** [comment]
Thank you @jtmiles !
