### ISSUE TITLE
Event syncronization

### ISSUE THREAD

**Issue by ananmoran** [open-ephys/GUI#385]
Hi,
I am using Neuropixels and have different streams recorded, both the hipass AP and the LFP, as well as digital signals using a NI acquisition board, all boards reside in the same NI box. I configured the synchronization in the recording node, and all squares are green, signaling correct synchronization. Following recording I can see synchronized_timestamps.npy in all continuous channels, but not in the events/TTL channels. Is there a reason for that? What is the best way to perform event synchronization with the continuous signals, and consequently spike times?

Thanks
Anan

**Comment by jsiegle** [comment]
The TTL event timestamps refer to the same sample indices as `timestamps.npy` for the continuous data. So finding the relevant synchronized timestamp just involves two steps:

1) Subtract the very first timestamp, so the timestamps are shifted relative to the recording start index
2) Use the result to index into `synchronized_timestamps.npy`

In Python, this would be something like:

```python
event_ts = np.load('/path/to/event/timestamps.npy')
continuous_ts = np.load('/path/to/continuous/timestamps.npy')
synchronized_ts = np.load('/path/to/continuous/synchronized_timestamps.npy')

synchronized_event_ts = synchronized_ts[event_ts - continuous_ts[0]]
```

**Comment by ananmoran** [comment]
Hi Josh,
Thanks for your answer and code. Unfortunately using continuous_ts[0], the first sample of the continuous timestamps crashes with "out of bounds" error. However, I used the 0 time in the sync_messages.txt file to normalize the timestamps which gave better results. Does this seems a logical solution?

EDIT:
Some more info regarding this issue. 
I made a recording with the NP in which I simultaneously injected current to the medium of the electrode, and sent a TTL signal to the NI-DAQ card. The high-pass and low-pass signals are in sync, when using both their timestamps divided by their sampling rate (30000 and 2500 Hz, respectively), or using their synchronized_timestamps.npy.   However, using your method did not normalize the events correctly. First it caused an "Out of bounds" error due to the last event being outside the range of   synchronized_ts

synchronized_event_ts = synchronized_ts[event_ts - continuous_ts[0]]
IndexError: index 456858 is out of bounds for axis 0 with size 452988

I also tried to use the sampling rate to normalize the events it again worked for the the two continuous signals, but not for the TTL events. Subtracting the continuous_ts[0] from the events led to a 2 second delay (red vertical lines), while subtracting the zero time of the daq found in the sync_messages.txt gave better results (black lines), but not fully accurate. I must say that using this method on a different recording gave negative event times, which tells me I am probably on the wrong track.
![Capture](https://user-images.githubusercontent.com/8314287/107524783-d8c9e380-6bbe-11eb-8f37-f5f7bad79856.PNG)

Please advice

Thanks
Anan

**Comment by jsiegle** [comment]
Are `synchronized_ts` and `continuous_ts` from the NIDAQ sub-processor or the Neuropixels sub-processor? If the TTLs came through the NIDAQ card, both of those need to come from the NIDAQ as well.

**Comment by ananmoran** [comment]
They are from the NIDAQ. I have tested again following your instructions and it works perfectly!
Thanks Josh
