### ISSUE TITLE
event_listener.py update?

### ISSUE THREAD

**Issue by pplenck** [open-ephys/GUI#386]
Hello
I found your event_listener.py into the repository (python)
https://github.com/open-ephys/GUI/tree/master/Resources/Python
and there seems to be an old, unresolved issue.
there is a remnant of a conversation between Aaron and Marcus on the google group
basically it gets stuck  on line 80:
 parts = sock.recv_multipart()

Aaron wrote 
"The reason it gets stuck at that specific line is because in lines 68-69 the script first sets up listeners for the 4 event types specified in lines 13-17, each of those listener filtering each message according to its first byte. The first byte of an event messages is not any of those any more, but 1 for normal events and 2 for spike events, with a second byte specifying the "subtype" (TTL/TEXT, etc... for events and SINGLE/STEREOTRODE/TETRODE for spikes)."

Has anyone updated the code to fit the new version of the event broadcaster?
thanks for the input

**Comment by jsiegle** [comment]
The latest version of `event_listener.py` now lives here: https://github.com/open-ephys/open-ephys-python-tools/blob/main/open_ephys/streaming/event_listener.py

If you're still experiencing this problem, please open an issue in the [`open-ephys-python-tools`](https://github.com/open-ephys/open-ephys-python-tools) repository.
