### ISSUE TITLE
Strange LED warming up time course

### ISSUE THREAD

**Issue by polbech** [open-ephys/GUI#389]
Hello! 

I am currently using two Cyclops to deliver alternated pulsed light (8ms pulses) from 2 LEDs for imaging. I have noticed in my images a consistent artifact in the normalized fluorescence where it seems that a considerable number of frames start from very negative values. When checking the raw fluorescent traces in non-biological samples, it seems that the intensity of one of the LEDs progressively ramps up over the initial ~ 20 frames. The other LED shows an opposing trend, starting up higher and ramping down over a longer time span. Initially I figured it might be from the controller but when I checked in the oscilloscope, the output pulses seem to work fine. Image corresponds to an example of the fluorescent traces in a non biological sample, x axis represents frames, and y axis is normalized fluorescence.

![image](https://user-images.githubusercontent.com/65780058/119462496-12bf8f80-bd41-11eb-9431-2d39d71e07c0.png)

With my limited knowledge about LEDs, I have figured out that at least the ramping down trend could be a junction temperature issue, but I still don't know if the ramping up behaviour is expected, if it can be fixed by compensating with the driver pulses, or if I should just replace the LED altogether. Has anyone observed a similar type of behaviour with their LEDs? Can this be fixed, perhaps compensating by tweaking the output from the driver in the initial frames, or should I just replace the LED altogether? In case this is an intrinsic LED thing, what would be the best way to correct this to minimize the contamination during real acquisition?

Thank you very much in advance and let me know if I can provide any further information!
Best,
Pol

PS: I am using the Luxeon Star LEDs from Quadica attached to a cylindrical aluminum heat sink with fins spanning the whole perimeter.

**Comment by jonnew** [comment]
Hi,

Can you copy/paste this question  into the cyclops repo: https://github.com/jonnew/cyclops?
