### ISSUE TITLE
openephys GUI doesn't open (white screen no error messages) 

### ISSUE THREAD

**Issue by yves-weissenberger** [open-ephys/GUI#392]
last line in the console is Num engines:2 --> reinstalling doesn't help 

has anyone encountered this issue?

**Comment by jsiegle** [comment]
If you delete `lastConfig.xml` and `recoveryConfig.xml` from `C:\ProgramData\Open Ephys`, does it fix the problem? Those are not overwritten when reinstalling.

**Comment by veronikasamborska1994** [comment]
I deleted the Open Ephys folder altogether and that hasn't helped :(

**Comment by jsiegle** [comment]
Were you able to run the GUI successfully at any point on this computer?

**Comment by veronikasamborska1994** [comment]
Yes, this is the really strange thing. It was working just an hour ago while I was recording from the same setup. It's very hard to understand what happened as there don't seem to be any errors.

**Comment by jsiegle** [comment]
Are you installing from a .zip file or via the installer executable?

**Comment by veronikasamborska1994** [comment]
so this was extremely stupid but I guess it might be useful for people who don't use windows machines for anything other than recording data like me. I still don't entirely understand why but despite the GUI being opened the actual window was hidden so it was just a matter of clicking nervously (though I am sure there is a specific shortcut) on things for it to pop back up. thanks a lot for your help though! :)

**Comment by lachioma** [comment]
It happened something similar to me: the GUI would not show up, only the console, and I could see just a white screen of the GUI when previewing it at the taskbar (hovering the mouse on the open ephys app in the taskbar), nothing else. In my case, I had a second monitor connected but not in use. I solved by disabling that screen in the Windows screen settings and by right-clicking on the preview + "Maximize".
