### ISSUE TITLE
All channels in LFP viewer are the same

### ISSUE THREAD

**Issue by YadongD** [open-ephys/GUI#393]
Hi, 

I am new to ephys study and the Open-Ephys system. I'm using GUI v0.5.5. Recently. 
I plugged in two animals, both are with 64 channels. My problem right now is when starting acquisition, the data of all channels from the LFP viewer looks the same(I would say these same signals have spike patterns). I don't know if there are any specific settings in the GUI that might help solve this or it might be some other reasons. 

Thank you! 

Best, 
Yadong

**Comment by jsiegle** [comment]
Same issue as https://github.com/open-ephys/plugin-GUI/issues/479, closing this one
