### ISSUE TITLE
unable to find impedance_measurement.xml

### ISSUE THREAD

**Issue by edmundchong** [open-ephys/GUI#399]
Hi, 

I tried saving the impedance measurements by checking the "save impedance measurements" option (tick mark displayed), also alternatively tried "Measure impedance at acquisition start" and then started a recording. In the debug console it does say "Saving impedance measurements in \impedance_measurement.xml", however, I cannot find this file -- whether in the recording directory, or openephys directories, or doing a search for that named file in my drive.

thanks!
-Edmund

**Comment by jsiegle** [comment]
I believe the impedance saving stopped working after we switched to the plugin-like Record Node modules in v0.5.0.

In the next major release (0.6.0), it's possible to save the impedance values to an XML file directly from the user interface. You can find a preview version here: https://openephysgui.jfrog.io/artifactory/Test/windows/open-ephys-v0.6.0-rc2-windows-beta.zip. If you select "Acquisition Board" as a default configuration, it should install that plugin automatically ("Rhythm FPGA" has been renamed "Acquisition Board" in this release).

We are planning to release the official version in the next few weeks, but in the meantime you could use v0.6.0 to calculate and save the impedance values, and then switch back to whichever version you're using now. 0.6.0 won't overwrite any of your existing configs or plugins, so you can use them side by side.

**Comment by jsiegle** [comment]
Version 0.6.0 is now officially released, and allows you to save the impedance XML files directly from the Acquisition Board plugin.
