### ISSUE TITLE
Audio Monitor not working in v0.6.0rc3-beta 

### ISSUE THREAD

**Issue by yaxigeigei** [open-ephys/GUI#401]
I thought I did the right thing but there's no audio being output. Please see this [video](https://www.dropbox.com/s/vt1rke7jk5dytkc/2022-04-28%2015-06-37%20no%20audio.mp4?dl=0) for details.

**Comment by jsiegle** [comment]
The audio monitor can't be at the end of the signal chain...if you move it over by one it should work!

We will have this documented soon.

**Comment by yaxigeigei** [comment]
Perfect, it works!
