### ISSUE TITLE
LFP viewer freezing at .2s timebase

### ISSUE THREAD

**Issue by interpretivechaos** [open-ephys/GUI#41]
The update on LFP viewer is choppy (freezing for seconds at a time) at .2s time base. Perhaps relatedly, Open-Ephys seems to be taking up a lot more CPU recently, only when LFP viewer is active.

**Comment by jvoigts** [comment]
think this should be less on an issue now on the updated lfpviewer in the main repo - please re-open an issue there if the problem persists, might eventually require this: https://github.com/open-ephys/plugin-GUI/issues/18
