### ISSUE TITLE
Add feature to increase displayed event length

### ISSUE THREAD

**Issue by jvoigts** [open-ephys/GUI#49]
Currently, short events are often not drawn because they fall under 1px, add a buffer state to solve this. This could/should probably be solved by generally adding supersampling to the LFP display.

**Comment by jsiegle** [comment]
LFP Viewer event display has improved a lot, but very short events can still get lost. If this is a problem for your experiments, please re-open this issue in the [`plugin-GUI`](https://github.com/open-ephys/plugin-GUI) repo.
