### ISSUE TITLE
Events are sometimes categorized to the wrong channel

### ISSUE THREAD

**Issue by jvoigts** [open-ephys/GUI#50]
Occasionally, events from a given channel (5 in my case right now) are also displaying a short event on another channel (2 here). The 5->2 mapping seems to be pretty consistent here, but the error only occurs ~5% of the time. I am not seeing the issue on Reid's software so it looks like it's a software bug.

Still have to test if the error is display specific or if it occurs in the saved event files as well.

**Comment by jsiegle** [comment]
This has now been fixed.
