### ISSUE TITLE
On-board audio monitor only works for headstage port A

### ISSUE THREAD

**Issue by open-ephys** [open-ephys/GUI#57]
Inside the Rhythm source module, selecting one or two channels for audio monitoring only works if the data is coming from port A. We need to add something that checks which headstage is sending data and updates the channel number accordingly.

**Comment by AGenews** [comment]
any news on this?

**Comment by jsiegle** [comment]
The source code for the Rhythm Plugins (Acquisition Board and Intan RHD USB) now live here: https://github.com/open-ephys-plugins/rhythm-plugins

If you're still experiencing any problems with this plugins, please open a new issue in that repository.
