### ISSUE TITLE
Selective Compilation

### ISSUE THREAD

**Issue by ckemere** [open-ephys/GUI#61]
Do we have a multiplatform approach for selectively including different modules in the compilation?

I'm starting from scratch on an OSX installation, and ftdi is currently a dependency. But of course the base system doesn't require it anymore, and so I'd like to make it optional. I can do this with #defines, but I'm wondering if there's some sort of cmake or autotools structure we're using...

**Comment by jsiegle** [comment]
Nearly all external dependencies have now been migrated to separate plugin repositories, so the core application only depends on Juce.
