### ISSUE TITLE
Weird behavior if laptop is ungrounded

### ISSUE THREAD

**Issue by ckemere** [open-ephys/GUI#64]
I'm running the OE OSX binary release on a 2013 MB Air. When I run with either the laptop powered or plugged into an external display, everything is happy. However, if I run with the laptop un connected, I see what I think are data lock errors (triangular noise ~1000 uV P-P on all channels). If the input signal is larger than this noise, it still shows up, but not otherwise. Also, the preamp has reference and ground shorted.

**Comment by jvoigts** [comment]
this is now mostly covered by  https://open-ephys.atlassian.net/wiki/display/OEW/Debugging+recording+noise
