### ISSUE TITLE
AUDIO and REC selection tabs in channel selection drawers do not work

### ISSUE THREAD

**Issue by jennisiegel** [open-ephys/GUI#65]
I'm running in OSX (mountain lion). When I click on either the Audio or Rec tabs in the channel selector drawer in any of the Sink modules they do not appear to work (this is true for LFP as well as SpikeViewer). Therefore, I am unable to save any continuous recording data because I cannot choose this option. Everything else appears to be ok so far. I initially observed this when using the FileReader as a Source, but it was also the case if I just acquired noise from the acq board. Any suggestions? I downloaded the GUI just this morning.

**Comment by jsiegle** [comment]
These tabs have now been deprecated. See [this page](https://open-ephys.github.io/gui-docs/User-Manual/Whats-new-in-version-06X.html) for more info about channel selection in the latest version of the GUI.
