### ISSUE TITLE
Digital Output pulses

### ISSUE THREAD

**Issue by ckemere** [open-ephys/GUI#77]
I have verified that the API code for digital output and the HDMI breakout boards. 

To be useful as a trigger, we'd like to have a configurable pulse, though. Could do in software, but should be fairly easy to do in HW.

**Comment by jsiegle** [comment]
The **Acq. Board Output** (available after installing [Rhythm Plugins](https://github.com/open-ephys-plugins/rhythm-plugins)) can now be used to control the acquisition board's digital outputs from software.
