### ISSUE TITLE
Is there global tracking of time?

### ISSUE THREAD

**Issue by ckemere** [open-ephys/GUI#78]
Say for instance that I want to generate a ~100 ms TTL pulse. I can raise and lower TTL outputs via the hardware interface, but I'm curious if the incoming timestamps are maintained in any sort of object-global way...

**Comment by jsiegle** [comment]
The latest version of the GUI includes support for global timestamps (in seconds), in addition to the sample number timestamps that were used previously.

Currently, this is only used by the Record Node, which can use simultaneously detected TTL events to synchronize different data streams online. All data saved by the Record Node includes both the sample number as well as the global timestamp for each spike/event/continuous sample.
